# Generated by Django 5.0.3 on 2024-03-09 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('duracao', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Prestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('servicos', models.ManyToManyField(to='core.servico')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField()),
                ('inicio', models.TimeField()),
                ('fim', models.TimeField()),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.prestador')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('status', models.CharField(choices=[('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('concluido', 'Concluído')], max_length=50)),
                ('notas', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_cliente', to=settings.AUTH_USER_MODEL)),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_prestador', to='core.prestador')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servico')),
            ],
        ),
    ]
