# Generated by Django 5.0.3 on 2024-03-17 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_reserva_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nome_completo',
        ),
    ]
